theme: jekyll-theme-slate
title: Welcome to Jorge's homepage!
description: Feel free to bookmark this to keep an eye on my project updates

https://github.com/JorgeTejadaBSU/hello-world.git
[GitHub](https://github.com/JorgeTejadaBSU/hello-world.git)
